name: 'Dependabot Changelog Helper'
description: |
  "Helps keep your repository uo-to-date when Dependabot updates your dependencies."
author: '@dangoslen'
inputs:
  version:
    description: |
      "The version to find in the CHANGELOG to add dependabot entries to"
    required: true
    default: "UNRELEASED"
  changelogPath:
    description: |
      "The path to the CHANGELOG file to add dependabot entries to"
    required: true
    default: './CHANGELOG.md'
  activationLabel:
    description: |
      "DEPRECATED! Please use `activationLabels` instead. The label to indicate that the action should run"
    required: true
    default: ''
  activationLabels:
    description: |
      "The labels to activate/run this action. Labels are comma-separated. Each label must be present on the pull request for the action to run."
    required: true
    default: 'dependabot'
  entryPrefix:
    description: |
      "The prefix word (after the hyphen) of the changelog entry, for example: '- [entryPrefix] `dependency` from v1.0 to v2.0'"
    required: true
    default: 'Bump'
  sectionHeader:
    description: |
      "The section header to add the changelog entry under"
    required: true
    default: 'Dependencies'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  color: green
  icon: edit
