name: 'Dependabot Changelog Helper'
description: |
  "Helps keep your repository uo-to-date when Dependabot updates your dependencies."
author: '@dangoslen'
inputs:
  version:
    description: |
      "The version to find in the CHANGELOG to add dependabot entries to"
    required: true
    default: "UNRELEASED"
  changelogPath:
    description: |
      "The path to the CHANGELOG file to add dependabot entries to"
    required: true
    default: './CHANGELOG.md'
  activationLabel:
    description: |
      "The label to indicate that the action should run"
    required: true
    default: 'dependabot'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  color: green
  icon: edit
