name: 'Dependabot Helper'
description: |
  "Helps keep your repository uo-to-date when Dependabot updates your dependencies."
author: '@dangoslen'
inputs:
  version:
    description: |
      "The version to find in the CHANGELOG to add dependabot entries underneath"
    required: true
    default: "UNRELEASED"
  changelogPath:
    description: |
      "The path to the CHANGELOG file to add dependabot entries to"
    required: true
    default: './CHANGELOG.md'
  activationLabel:
    description: |
      "The label to indicate that the Dependabot Helper should run"
    required: true
    default: 'dependencies'
  newVersionLineNumber:
    description: |
      "If the desired version is not found in the file, this is the default line number (0-indexed) in which to place the new version"
    required: true
    default: 2
runs:
  using: 'node12'
  main: 'dist/index.js'
