name: count-action-users

on:
  schedule:
    - cron: '0 4 * * *'
  workflow_dispatch:

jobs:
  count:
    runs-on: ubuntu-latest
      
    steps:
    - uses: actions/checkout@v4
      with:
        ref: gh-pages 

    - name: Generate user count JSON endpoint
      uses: cicirello/count-action-users@v1
      with:
        action-list: dangoslen/dependabot-changelog-helper 
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}